# Preface {.unnumbered}

Hello!

I am glad your found your way to this book as is tells me you are beginning to use the scan package. While `scan` is quiet thoroughly developed, this book is at an early stage. I am continuously working on it and extending it. At this point in time there is no release of this book available. Only this draft which is full of errors (code and typos).\
If you have any suggestions how to enhance the book or would like to report errors, comments, feedback etc. you can do so by posting an issue to the gitHub repository of this book. You can find the repository at <https://github.com/jazznbass/scan-Book>.

Thank you!

Jürgen

`r format(Sys.time(), "%d %B %Y")`

## Software reference {.unnumbered}

This book has been created using the `Rmarkdown` [@R-rmarkdown] and `bookdown` [@R-bookdown] packages within the RStudio [@RStudio] environment. The analyses have been conducted with the **R** package `scan` at version `r packageVersion("scan")` [@R-scan]. `r R.version$version.string` was used [@R-base].
