```{r include = FALSE}
build <- yaml::read_yaml("_build.yml")
build$build <- as.integer(build$build + 1)
build$date <- as.character(Sys.time())
build$scan_version <- packageVersion("scan") |> as.character()
build$scplot_version <- packageVersion("scplot") |> as.character()
build$r_version <- gsub("R version ", "", R.version.string)
yaml::write_yaml(build, "_build.yml")
```

***Version `r build <- yaml::read_yaml("_build.yml"); paste0(build$version, " (build ", build$build,")")`***

::: callout-note
Please support open-access publishing by citing this work:

Wilbert, J. (2025). *Analyzing single-case data with R and scan*. doi: 10.5281/zenodo.14950444. <https://jazznbass.github.io/scan-Book/>
:::

# Preface {.unnumbered}

Welcome dear readers!

I am delighted to see that you have discovered this book - it suggests that you interested in single-case research and have begun to explore the *scan* package. This book pursues two maingoals: First, it is a practical manual for using the *scan* package in R. Second, it offers a comprehensive overview of methods and approaches to analysze single-case data.

While scan has undergone extensive development, this book is still a work in progress (approximately 60% complete) and I am continuously expanding its content. At present, there is no official release version - only this draft, which may contain errors.

If you have any suggestions for improving the book, wish to report a bug, or provide comments, feedback, and more, please visit the GitHub repository of this book and contribute here:\
<https://github.com/jazznbass/scan-Book/discussions.>

Thank you very much!

Jürgen

`r format(Sys.time(), "%d %B %Y")`

## General references {.unnumbered}

This book has been created using [`Quarto`](https://quarto.org/) within the RStudio [@RStudio] environment. The analyses have been conducted with the **R** package `scan` at version `r packageVersion("scan")` [@R-scan] and `scplot` at version `r packageVersion("scplot")` [@R-scplot]. `r R.version$version.string` was used [@R-base].

Note: The cover has been designed by Tony Wilbert and Henry Ritter.\
Thanx for that!
