
# Introduction

Single case research has become an important and broadly accepted method for gaining insight into educational processes. Especially the field of special education has adopted single-case research as a proper method for evaluating the effectiveness of an intervention or the developmental processes underlying problems in acquiring academic skills. Single-case studies are also popular among teachers and educators who are interested in evaluating the learning progress of their students. The resulting information of a single-case research design provide helpful information for pedagogical decision processes regarding further teaching processes of an individual student but also help to decide, whether or how to implement certain teaching methods into a classroom.

This book has been created using the `Rmarkdown` [@R-rmarkdown] and `bookdown` [@R-bookdown] environment.
The analyses have been conducted with the **R** package `scan` at version `r packageVersion("scan")` [@R-scan].

`r R.version$version.string` was used [@R-base].




